version: '3'

services:
  ngiinx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - consultant_static_volume:/consultant/static
      - consultant_files_volume:/consultant/files
    networks:
      - nginx_network

volumes:
  consultant_static_volume:
    external: true
  consultant_files_volume:
    external: true
networks:
  nginx_network:
    external: true